apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
{{- if .Values.mysql.storageClass }}
  storageClassName: "{{ .Values.mysql.storageClass }}"
{{- end }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage }}
      